# Generated by Django 4.0.4 on 2022-06-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterField(
            model_name='book',
            name='copies_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='books_pdf/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(max_length=1000),
        ),
    ]
