# Generated by Django 4.0.4 on 2022-06-30 07:16

import common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_alter_category_options_alter_book_copies_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=common.upload_location),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to=common.upload_location),
        ),
    ]
