# Generated by Django 4.0.4 on 2022-07-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_alter_book_image_alter_book_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='userbook',
            old_name='user_id',
            new_name='user',
        ),
    ]
