# Generated by Django 4.0.4 on 2022-07-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_rating', '0001_initial'),
        ('ebooks', '0004_alter_userbook_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebooks.book'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='comment_rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_rating.commentrating'),
        ),
    ]
