# Generated by Django 4.0.4 on 2022-07-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_rating', '0001_initial'),
        ('ebooks', '0005_alter_userbook_book_alter_userbook_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ebooks.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbook',
            name='comment_rating',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='comment_rating.commentrating'),
            preserve_default=False,
        ),
    ]
