# Generated by Django 4.0.4 on 2022-07-05 03:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebooks', '0007_remove_userbook_comment_rating_userbook_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'book')},
        ),
    ]
