# Generated by Django 4.0.4 on 2022-07-06 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0008_alter_userbook_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='comment',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
